#auto: true

#markdown: rdiscount
#markdown: redcarpet
markdown: Kramdown
highlight: true
paginate: 8
permalink: /:title

title: 以生为书
url: http://oraant.github.io
feed: /atom.xml
author_info: <a href="http://oraant.github.io/">OraAnt</a>

gems: [jekyll-paginate]
